defaults: &defaults
  db_path: data/dummy
  dropbox:
    app_key:      <%= ENV['DROPB_APP_KEY'] %>
    app_secret:   <%= ENV['DROPB_APP_SECRET'] %>
    access_token: <%= ENV['DROPB_TOKEN'] %>
    api_logging:  <%= !!ENV['DROPB_API_LOG'] %>

development:
  <<: *defaults
  db_path: data/level_dev

test:
  <<: *defaults
  db_path: data/level_test

staging:
  <<: *defaults
  db_path: data/level_staging

production:
  <<: *defaults
  db_path: data/level_prod
